# Generated by Django 5.1.7 on 2025-11-22 10:39

import datetime
import django.db.models.deletion
import phonenumber_field.modelfields
import tennants.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('number_of_houses', models.IntegerField(db_index=True, default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(db_index=True, max_length=5)),
                ('house_size', models.CharField(default='1 bedroom', max_length=10)),
                ('house_rent_amount', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=10)),
                ('deposit_amount', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=10)),
                ('occupation', models.BooleanField(default=False)),
                ('flat_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='tennants.flatbuilding')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=50)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, unique=True)),
                ('id_number', models.CharField(max_length=10, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rent_due_date', models.DateField(default=datetime.datetime.now)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='tennants.house')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('year', models.IntegerField(db_index=True, default=tennants.models.RentPayment.current_year)),
                ('rent_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], default='cash', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rent_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_payments', to='tennants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(editable=False)),
                ('payment_method', models.CharField(max_length=50)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='tennants.house')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rent_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tennants.rentpayment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='tennants.tenant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='house',
            constraint=models.UniqueConstraint(fields=('flat_building', 'house_number'), name='unique_house_per_building'),
        ),
        migrations.AlterUniqueTogether(
            name='rentpayment',
            unique_together={('tenant', 'rent_month', 'year')},
        ),
    ]
