# Generated by Django 5.1.7 on 2025-08-26 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tennants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flatbuilding',
            name='how_many_occupied',
        ),
        migrations.RemoveField(
            model_name='flatbuilding',
            name='vacant_houses',
        ),
    ]
