# Generated by Django 5.1.7 on 2026-01-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
