# Generated by Django 5.1.7 on 2026-01-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennants', '0002_alter_payment_amount_alter_payment_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentcharge',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='last_notification_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='reminder_days_before',
            field=models.IntegerField(db_index=True, default=3),
        ),
        migrations.AddField(
            model_name='tenant',
            name='sms_notifications',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
