# Generated by Django 5.1.4 on 2025-02-08 13:34

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tennants", "0007_alter_tennant_id_number_paymenthistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rentpayment",
            name="amount",
        ),
        migrations.AlterField(
            model_name="tennant",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                db_index=True, max_length=128, region=None, unique=True
            ),
        ),
    ]
