# Generated by Django 5.1.7 on 2025-04-26 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennants', '0008_remove_rentpayment_amount_alter_tennant_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tennant',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tennants', to='tennants.house'),
        ),
    ]
