# Generated by Django 5.1.7 on 2025-04-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennants', '0009_alter_tennant_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tennant',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
