# Generated by Django 5.1.7 on 2025-05-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennants', '0011_alter_tennant_balance'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='house',
            constraint=models.UniqueConstraint(fields=('flat_building', 'house_num'), name='unique_house_per_building'),
        ),
    ]
