# Generated by Django 5.1.7 on 2025-05-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennants', '0015_alter_flatbuilding_user_alter_house_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='house_num',
            field=models.CharField(max_length=5),
        ),
    ]
